// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMSBilling.Data;

#nullable disable

namespace TMSBilling.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250630043017_AddCustomerTable02")]
    partial class AddCustomerTable02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TMSBilling.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ACTIVE_FLAG")
                        .HasColumnType("int");

                    b.Property<string>("CUST_ADDR1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUST_ADDR2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUST_CITY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUST_CODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CUST_CUTOFF")
                        .HasColumnType("int");

                    b.Property<string>("CUST_EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUST_FAX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUST_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CUST_PIC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUST_TEL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ENTRY_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("ENTRY_USER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAIN_CUST")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TAX_REG_NO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_USER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TRC_CUSTOMER");
                });

            modelBuilder.Entity("TMSBilling.Models.CustomerGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CUST_CODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ENTRY_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("ENTRY_USER")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SUB_CODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_USER")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("TRC_CUST_GROUP");
                });

            modelBuilder.Entity("TMSBilling.Models.CustomerMain", b =>
                {
                    b.Property<string>("MAIN_CUST")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CUST_ADDR1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CUST_ADDR2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CUST_CITY")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CUST_EMAIL")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CUST_FAX")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CUST_NAME")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CUST_PIC")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CUST_TEL")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ENTRY_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("ENTRY_USER")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("STATUS_FLAG")
                        .HasColumnType("int");

                    b.Property<string>("TAX_IMG")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TAX_REG_NO")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_USER")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MAIN_CUST");

                    b.ToTable("TRC_CUSTOMER_MAIN");
                });

            modelBuilder.Entity("TMSBilling.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
