// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMSBilling.Data;

#nullable disable

namespace TMSBilling.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251007084257_AddIsGarageConsignee")]
    partial class AddIsGarageConsignee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TMSBilling.Controllers.OrderSummaryViewModel", b =>
                {
                    b.Property<string>("CneeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdSeq")
                        .HasColumnType("int");

                    b.Property<string>("InvNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("McEasyOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("OrderStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("OriginId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCustId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalItem")
                        .HasColumnType("int");

                    b.Property<int?>("TotalQty")
                        .HasColumnType("int");

                    b.Property<string>("WhCode")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("TMSBilling.Models.AreaGroup", b =>
                {
                    b.Property<int>("id_seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_seq"));

                    b.Property<string>("area_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("entry_user")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_seq");

                    b.ToTable("TRC_AREA_GROUP");
                });

            modelBuilder.Entity("TMSBilling.Models.ChargeUom", b =>
                {
                    b.Property<int>("id_seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_seq"));

                    b.Property<string>("charge_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("entry_user")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_seq");

                    b.ToTable("TRC_CHARGE_UOM");
                });

            modelBuilder.Entity("TMSBilling.Models.Config", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("entrydate")
                        .HasColumnType("datetime2");

                    b.Property<string>("entryuser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("hostname")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("port")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("protocol")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("updateuser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("TRC_CONFIG");
                });

            modelBuilder.Entity("TMSBilling.Models.Consignee", b =>
                {
                    b.Property<string>("CNEE_CODE")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte?>("ACTIVE_FLAG")
                        .HasColumnType("tinyint");

                    b.Property<string>("ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AREA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CATEGORY")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CITY")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CNEE_ADDR1")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CNEE_ADDR2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CNEE_ADDR3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CNEE_ADDR4")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CNEE_FAX")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CNEE_NAME")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CNEE_PIC")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CNEE_TEL")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CORDINATES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ENTRY_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("ENTRY_USER")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool?>("IS_GARAGE")
                        .HasColumnType("bit");

                    b.Property<string>("MCEASY_CUST_ID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MCEASY_GEOFENCE_ID")
                        .HasColumnType("int");

                    b.Property<string>("POSTAL_CODE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PROVINCE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RADIUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUB_CODE")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TAX_REG_NO")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_USER")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CNEE_CODE");

                    b.ToTable("TRC_CONSIGNEE");
                });

            modelBuilder.Entity("TMSBilling.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ACTIVE_FLAG")
                        .HasColumnType("int");

                    b.Property<int>("API_FLAG")
                        .HasColumnType("int");

                    b.Property<string>("CUST_ADDR1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUST_ADDR2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUST_CITY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUST_CODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CUST_CUTOFF")
                        .HasColumnType("int");

                    b.Property<string>("CUST_EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUST_FAX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUST_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CUST_PIC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUST_TEL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ENTRY_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("ENTRY_USER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAIN_CUST")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MCEASY_CUST_ID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TAX_REG_NO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_USER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TRC_CUSTOMER");
                });

            modelBuilder.Entity("TMSBilling.Models.CustomerGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CUST_CODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ENTRY_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("ENTRY_USER")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MCEASY_CUST_ID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SUB_CODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_USER")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("TRC_CUST_GROUP");
                });

            modelBuilder.Entity("TMSBilling.Models.CustomerMain", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CUST_ADDR1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CUST_ADDR2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CUST_CITY")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CUST_EMAIL")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CUST_FAX")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CUST_NAME")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CUST_PIC")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CUST_TEL")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ENTRY_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("ENTRY_USER")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MAIN_CUST")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("STATUS_FLAG")
                        .HasColumnType("int");

                    b.Property<string>("TAX_IMG")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TAX_REG_NO")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_USER")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.ToTable("TRC_CUSTOMER_MAIN");
                });

            modelBuilder.Entity("TMSBilling.Models.Destination", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("area")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("dest_loccode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("destination_code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("entrydate")
                        .HasColumnType("datetime2");

                    b.Property<string>("entryuser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("updateuser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("TRC_DESTINATION");
                });

            modelBuilder.Entity("TMSBilling.Models.Driver", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("date_entry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("date_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("driver_address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("driver_birth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("driver_date_terminate")
                        .HasColumnType("datetime2");

                    b.Property<string>("driver_id")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("driver_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("driver_nik")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("driver_photo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("driver_remark")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("driver_sim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("driver_sim_exp")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("driver_status")
                        .HasColumnType("tinyint");

                    b.Property<string>("terminate_reason")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("user_entry")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("user_update")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("vehicle_type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("vendor_id")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("TRC_DRIVER");
                });

            modelBuilder.Entity("TMSBilling.Models.Job", b =>
                {
                    b.Property<int>("id_seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_seq"));

                    b.Property<decimal?>("buy1")
                        .HasColumnType("money");

                    b.Property<decimal?>("buy2")
                        .HasColumnType("money");

                    b.Property<decimal?>("buy3")
                        .HasColumnType("money");

                    b.Property<decimal?>("buy_cc")
                        .HasColumnType("money");

                    b.Property<decimal?>("buy_diffa")
                        .HasColumnType("money");

                    b.Property<decimal?>("buy_ep")
                        .HasColumnType("money");

                    b.Property<decimal?>("buy_ov")
                        .HasColumnType("money");

                    b.Property<decimal?>("buy_rc")
                        .HasColumnType("money");

                    b.Property<decimal?>("buy_trip2")
                        .HasColumnType("money");

                    b.Property<decimal?>("buy_trip3")
                        .HasColumnType("money");

                    b.Property<string>("charge_uom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("charge_uom_c")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("charge_uom_v")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("container_no")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("cust_ori")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("dest_id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("dest_ori")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("driverhp")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("drivername")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("drop_seq")
                        .HasColumnType("int");

                    b.Property<DateTime?>("dvdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("entry_user")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("flag_cc")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("flag_charge")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("flag_diffa")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("flag_ep")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("flag_ov")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("flag_pu")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("flag_rc")
                        .HasColumnType("tinyint");

                    b.Property<string>("inv_no")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("job_status")
                        .HasColumnType("int");

                    b.Property<string>("jobid")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("moda_req")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte?>("multidrop")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("multitrip")
                        .HasColumnType("tinyint");

                    b.Property<string>("origin_id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("origin_ori")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ritase_seq")
                        .HasColumnType("int");

                    b.Property<decimal?>("sell1")
                        .HasColumnType("money");

                    b.Property<decimal?>("sell2")
                        .HasColumnType("money");

                    b.Property<decimal?>("sell3")
                        .HasColumnType("money");

                    b.Property<decimal?>("sell_cc")
                        .HasColumnType("money");

                    b.Property<decimal?>("sell_diffa")
                        .HasColumnType("money");

                    b.Property<decimal?>("sell_ep")
                        .HasColumnType("money");

                    b.Property<decimal?>("sell_ov")
                        .HasColumnType("money");

                    b.Property<decimal?>("sell_rc")
                        .HasColumnType("money");

                    b.Property<decimal?>("sell_trip2")
                        .HasColumnType("money");

                    b.Property<decimal?>("sell_trip3")
                        .HasColumnType("money");

                    b.Property<string>("serv_moda")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("serv_req")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("servtype_ori")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("truck_size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("truckid")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("trucksize_ori")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_user")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("vendor_job")
                        .HasColumnType("tinyint");

                    b.Property<string>("vendorid")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("vendorid_act")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_seq");

                    b.ToTable("TRC_JOB");
                });

            modelBuilder.Entity("TMSBilling.Models.JobHeader", b =>
                {
                    b.Property<int>("id_seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_seq"));

                    b.Property<string>("charge_uom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("cust_group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deliv_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("dest")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("driver_name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("driver_phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("entry_user")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("is_vendor")
                        .HasColumnType("bit");

                    b.Property<string>("jobid")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("mceasy_job_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("multidrop")
                        .HasColumnType("bit");

                    b.Property<string>("origin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("serv_moda")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("serv_type")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("truck_no")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("truck_size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_user")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("vendor_act")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("vendor_plan")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("id_seq");

                    b.ToTable("TRC_JOB_H");
                });

            modelBuilder.Entity("TMSBilling.Models.JobPOD", b =>
                {
                    b.Property<int>("id_seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_seq"));

                    b.Property<DateTime?>("arriv_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("arriv_pic")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("arriv_time")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("entry_user")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("inv_no")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("jobid")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("outorigin_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("outorigin_time")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("pod_remark")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("pod_ret_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("pod_ret_pic")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("pod_ret_time")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("pod_send_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("pod_send_pic")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("pod_send_time")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte?>("pod_status")
                        .HasColumnType("tinyint");

                    b.Property<string>("spd_no")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_user")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_seq");

                    b.ToTable("TRC_JOB_POD");
                });

            modelBuilder.Entity("TMSBilling.Models.Order", b =>
                {
                    b.Property<int>("id_seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_seq"));

                    b.Property<string>("cnee_code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("delivery_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("dest_area")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("do_rcv_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("do_rcv_time")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("entry_user")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("inv_no")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("jobid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("mceasy_dest_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("mceasy_destination_address_id")
                        .HasColumnType("int");

                    b.Property<string>("mceasy_do_number")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("mceasy_is_upload")
                        .HasColumnType("bit");

                    b.Property<string>("mceasy_order_id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("mceasy_origin_address_id")
                        .HasColumnType("int");

                    b.Property<string>("mceasy_origin_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("mceasy_status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("moda_req")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte?>("order_status")
                        .HasColumnType("tinyint");

                    b.Property<string>("origin_id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("pallet_consume")
                        .HasColumnType("int");

                    b.Property<int?>("pallet_delivery")
                        .HasColumnType("int");

                    b.Property<DateTime?>("pickup_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("remark")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("serv_req")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("si_no")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("sub_custid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("tot_pkgs")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int?>("total_pkgs")
                        .HasColumnType("int");

                    b.Property<string>("truck_size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("uom")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_user")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("wh_code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_seq");

                    b.ToTable("TRC_ORDER");
                });

            modelBuilder.Entity("TMSBilling.Models.OrderDetail", b =>
                {
                    b.Property<int>("id_seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_seq"));

                    b.Property<string>("cnee_code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("delivery_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("entry_user")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("full_addres")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("gi_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_seq_order")
                        .HasColumnType("int");

                    b.Property<string>("inv_no")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("item_category")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("item_height")
                        .HasColumnType("int");

                    b.Property<int?>("item_length")
                        .HasColumnType("int");

                    b.Property<string>("item_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("item_qty")
                        .HasColumnType("int");

                    b.Property<decimal?>("item_wgt")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int?>("item_width")
                        .HasColumnType("int");

                    b.Property<int?>("koli_qty")
                        .HasColumnType("int");

                    b.Property<string>("mceasy_order_dtl_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mceasy_order_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mceasy_product_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pack_unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("pallet_qty")
                        .HasColumnType("int");

                    b.Property<string>("pkg_unit")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("pu_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("sub_custid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_user")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("wh_code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_seq");

                    b.ToTable("TRC_ORDER_DTL");
                });

            modelBuilder.Entity("TMSBilling.Models.Origin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("area")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("entrydate")
                        .HasColumnType("datetime2");

                    b.Property<string>("entryuser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("origin_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("origin_loccode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("updateuser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("TRC_ORIGIN");
                });

            modelBuilder.Entity("TMSBilling.Models.PriceBuy", b =>
                {
                    b.Property<int>("id_seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_seq"));

                    b.Property<byte?>("active_flag")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("buy1")
                        .HasColumnType("money");

                    b.Property<decimal?>("buy2")
                        .HasColumnType("money");

                    b.Property<decimal?>("buy3")
                        .HasColumnType("money");

                    b.Property<decimal?>("buy_cancel")
                        .HasColumnType("money")
                        .HasColumnName("buy_cancel");

                    b.Property<decimal?>("buy_diff_area")
                        .HasColumnType("money")
                        .HasColumnName("buy_diff_area");

                    b.Property<decimal?>("buy_ovnight")
                        .HasColumnType("money")
                        .HasColumnName("buy_ovnight");

                    b.Property<decimal?>("buy_ret_cargo")
                        .HasColumnType("money")
                        .HasColumnName("buy_ret_cargo");

                    b.Property<decimal?>("buy_ret_empt")
                        .HasColumnType("money")
                        .HasColumnName("buy_ret_empt");

                    b.Property<decimal?>("buytrip2")
                        .HasColumnType("money")
                        .HasColumnName("buytrip2");

                    b.Property<decimal?>("buytrip3")
                        .HasColumnType("money")
                        .HasColumnName("buytrip3");

                    b.Property<decimal?>("charge_min")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("charge_uom")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("curr")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("dest")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("entry_user")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("flag_min")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("flag_range")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("max_range")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("min_range")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("origin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("rate_value")
                        .HasColumnType("money");

                    b.Property<string>("serv_moda")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("serv_type")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("sup_code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("truck_size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_user")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("valid_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id_seq");

                    b.ToTable("TRC_PRICEBUY");
                });

            modelBuilder.Entity("TMSBilling.Models.PriceSell", b =>
                {
                    b.Property<int>("id_seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_seq"));

                    b.Property<byte?>("active_flag")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("charge_min")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("charge_uom")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("curr")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("cust_code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("dest")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("entry_user")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("flag_min")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("flag_range")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("max_range")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("min_range")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("origin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("rate_value")
                        .HasColumnType("money");

                    b.Property<decimal?>("sell1")
                        .HasColumnType("money");

                    b.Property<decimal?>("sell2")
                        .HasColumnType("money");

                    b.Property<decimal?>("sell3")
                        .HasColumnType("money");

                    b.Property<decimal?>("sell_cancel")
                        .HasColumnType("money")
                        .HasColumnName("sell_cancel");

                    b.Property<decimal?>("sell_diff_area")
                        .HasColumnType("money")
                        .HasColumnName("sell_diff_area");

                    b.Property<decimal?>("sell_ovnight")
                        .HasColumnType("money")
                        .HasColumnName("sell_ovnight");

                    b.Property<decimal?>("sell_ret_cargo")
                        .HasColumnType("money")
                        .HasColumnName("sell_ret_cargo");

                    b.Property<decimal?>("sell_ret_empty")
                        .HasColumnType("money")
                        .HasColumnName("sell_ret_empty");

                    b.Property<decimal?>("selltrip2")
                        .HasColumnType("money")
                        .HasColumnName("selltrip2");

                    b.Property<decimal?>("selltrip3")
                        .HasColumnType("money")
                        .HasColumnName("selltrip3");

                    b.Property<string>("serv_moda")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("serv_type")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("truck_size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_user")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("valid_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id_seq");

                    b.ToTable("TRC_PRICESELL");
                });

            modelBuilder.Entity("TMSBilling.Models.ServiceModa", b =>
                {
                    b.Property<int>("id_seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_seq"));

                    b.Property<DateTime?>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("entry_user")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("moda_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_seq");

                    b.ToTable("TRC_SERV_MODA");
                });

            modelBuilder.Entity("TMSBilling.Models.ServiceType", b =>
                {
                    b.Property<int>("id_seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_seq"));

                    b.Property<DateTime?>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("entry_user")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("serv_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_seq");

                    b.ToTable("TRC_SERV_TYPE");
                });

            modelBuilder.Entity("TMSBilling.Models.TruckSize", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("entrydate")
                        .HasColumnType("datetime2");

                    b.Property<string>("entryuser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("trucksize_code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("updateuser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("TRC_TRUCKSIZE");
                });

            modelBuilder.Entity("TMSBilling.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TMSBilling.Models.Vendor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<byte?>("ACTIVE_FLAG")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("ENTRY_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("ENTRY_USER")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SUP_ADDR1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SUP_ADDR2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SUP_CITY")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SUP_CODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SUP_EMAIL")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SUP_FAX")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SUP_NAME")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SUP_PIC")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SUP_TEL")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SUP_TYPE")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TAX_REG_NO")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_USER")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.ToTable("TRC_VENDOR");
                });

            modelBuilder.Entity("TMSBilling.Models.VendorTruck", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("entry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("entry_user")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("sup_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_user")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("vehicle_KIR")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("vehicle_KIR_exp")
                        .HasColumnType("datetime2");

                    b.Property<string>("vehicle_KTP")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("vehicle_SIM")
                        .HasColumnType("datetime2");

                    b.Property<string>("vehicle_STNK")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("vehicle_STNK_exp")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("vehicle_active")
                        .HasColumnType("tinyint");

                    b.Property<string>("vehicle_doortype")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("vehicle_driver")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("vehicle_emisi")
                        .HasColumnType("datetime2");

                    b.Property<string>("vehicle_merk")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("vehicle_no")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("vehicle_remark")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("vehicle_size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("vehicle_type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("TRC_VENDOR_TRUCK");
                });

            modelBuilder.Entity("TMSBilling.Models.Warehouse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("entrydate")
                        .HasColumnType("datetime2");

                    b.Property<string>("entryuser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("updateuser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("wh_code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("wh_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("TRC_WH");
                });
#pragma warning restore 612, 618
        }
    }
}
